INSERT INTO "app-db"."MATERIA_PRIMA" (ID,NOME,UNITA_DISPONIBILI,DIFFICOLTA_ESTRAZIONE,DIFFICOLTA_LAVORAZIONE) values (1,'FERRO',10000,25,20);
INSERT INTO "app-db"."MATERIA_PRIMA" (ID,NOME,UNITA_DISPONIBILI,DIFFICOLTA_ESTRAZIONE,DIFFICOLTA_LAVORAZIONE) values (2,'RAME',10000,10,5);
INSERT INTO "app-db"."MATERIA_PRIMA" (ID,NOME,UNITA_DISPONIBILI,DIFFICOLTA_ESTRAZIONE,DIFFICOLTA_LAVORAZIONE) values (3,'ZINCO',5000,10,10);
INSERT INTO "app-db"."MATERIA_PRIMA" (ID,NOME,UNITA_DISPONIBILI,DIFFICOLTA_ESTRAZIONE,DIFFICOLTA_LAVORAZIONE) values (4,'ORO',1000,55,40);
COMMIT;